// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Store.API.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.API.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Terrain in Medellín",
                            PurchaseDate = new DateTime(2023, 6, 27, 9, 37, 45, 799, DateTimeKind.Local).AddTicks(5399),
                            Status = false,
                            Type = 2,
                            Value = 60000000L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Libero 125cc",
                            PurchaseDate = new DateTime(2023, 6, 27, 9, 37, 45, 799, DateTimeKind.Local).AddTicks(5410),
                            Status = false,
                            Type = 1,
                            Value = 4000000L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Aparment in Itagüí",
                            PurchaseDate = new DateTime(2023, 6, 27, 9, 37, 45, 799, DateTimeKind.Local).AddTicks(5411),
                            Status = false,
                            Type = 3,
                            Value = 59000000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
